version: '3.7'
services:
  medication-wiki-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medication-wiki-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - medicationdb
    env_file:
      - .env

  medicationdb:
    image: postgres:13
    container_name: medicationdb
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - medicationdb:/var/lib/postgresql/data

volumes:
  medicationdb:
    name: medicationdb-postgres
